### ISSUE TITLE
Specials

### ISSUE THREAD

**Issue by djdirty60** [Dis90/plugin.video.discoveryplus#11]
Is it true that you cannot view the specials of the series, or cannot view them yet?

**Comment by Dis90** [comment]
Please provide link to content what is not available via addon.

**Comment by djdirty60** [comment]
![16110053004246267903680293751909](https://user-images.githubusercontent.com/13561831/104964331-7f65fe80-59dc-11eb-9ecc-54b9f8a4c1b5.jpg)
![16110053174853147438189972168859](https://user-images.githubusercontent.com/13561831/104964347-8a209380-59dc-11eb-9567-e2d91b051dd1.jpg)

But with all series, the special does not

**Comment by Dis90** [comment]
Are there specials on website from those shows? Post link to series where website lists specials and addon doesn't.

**Comment by djdirty60** [comment]
> Are there specials on website from those shows? Post link to series where website lists specials and addon doesn't.

https://www.discoveryplus.nl/programmas/gold-rush

**Comment by Dis90** [comment]
Tested and all of them lists specials in addon under series folder. So what is the problem? You can't play them?

**Comment by djdirty60** [comment]
No, they are not playable

**Comment by Dis90** [comment]
Okay. I found possible reason. They are tagged as "videoType" : "CLIP" and with Live TV fix they also should work now. Please try with newest version.

**Comment by djdirty60** [comment]
Its working, thnx
