### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by Tb3986** [Dis90/plugin.video.discoveryplus#23]
Hello,
i have a problem with login. 
I exported all my cookie with cookie editor, saved on txt file and imported on kodi but i get this splash:

https://i.postimg.cc/NFSXszQv/asd.jpg

Any idea?

Thank you

**Comment by Tb3986** [comment]
Ok, solved.
Thanks though

**Comment by dsgithub2k** [comment]
@Tb3986 how di you solved it?

**Comment by Tb3986** [comment]
> @Tb3986 how di you solved it?

Just choose your country on top. Mine was Finland and not Italy.
