### ISSUE TITLE
Channel error

### ISSUE THREAD

**Issue by Tb3986** [Dis90/plugin.video.discoveryplus#24]
Hello,
I can't open these channel: Discovery Channel, Science and Animal Planet

https://pastebin.com/YmXtEzwj

This is the log from Kodi

Regards

**Comment by Dis90** [comment]
What country are you in?

**Comment by Tb3986** [comment]
Italy.

**Comment by Dis90** [comment]
Download version with latest changes from Github. First select branch master or matrix and then Code -> Download ZIP

**Comment by Tb3986** [comment]
> Download version with latest changes from Github. First select branch master or matrix and then Code -> Download ZIP

ok works now thanks
Last bug i guess:
Video stream is only 720o and not 1080 like on website. Can be fixed?

**Comment by Dis90** [comment]
Good :) Check your Inputstream Adaptive settings. It handles video playback.
