### ISSUE TITLE
Philcyp

### ISSUE THREAD

**Issue by PhilCyp** [Dis90/plugin.video.discoveryplus#29]
Hi thank you for this addon. When I try to run it I get the following error message ' invalid arkrose token' and the addon won't launch.
Please can you tell me how to fix this-I have checked my discovery plus user name/password and they are entered correctly.I am running the latest version of Kodi on a windows 10 machine.
Thank you.

**Comment by Dis90** [comment]
That error comes because login page uses captcha.

Please read README:

> Login fails?
You can use cookies exported from Chrome to fix login issues. Use Get cookies.txt to export cookies and from addon settings specify location of cookies.txt.

**Comment by PhilCyp** [comment]
Great,That fixed it thank you!
I will look forward to using the addon.
