### ISSUE TITLE
[Feature Request] Add Setting to disable Sync

### ISSUE THREAD

**Issue by matthuisman** [Dis90/plugin.video.discoveryplus#30]
Quite a few people don't like what they are watching syncing up to Discovery+ for various reasons (sharing login with family etc)
Be great if you could add a setting to disable that behaviour :)

PR here (that should work)
https://github.com/Dis90/plugin.video.discoveryplus/pull/31

**Comment by Dis90** [comment]
This is something I have had in mind to add. Thanks for making PR :)

**Comment by matthuisman** [comment]
I'll update soon. One other small tweak as well as what you pointed out
