### ISSUE TITLE
Suggestions: Please add support of discoveryplus addon login for India.

### ISSUE THREAD

**Issue by rose-will** [Dis90/plugin.video.discoveryplus#33]
Developer this is a request from a user of your addon from india.
Could you please add support for the same addon for India ( country ) as I have the account but I'm not able to log in into my account from this addon in kodi.and if possible subtitles and audio language support for indian languages as available on discoveryplus app.

Many thanks in advance

**Comment by Dis90** [comment]
Yes it is possible but it would need help from developer from India because there's geoblock.

**Comment by Dis90** [comment]
Little status update. It wasn't actually same as US version. It is more like european versions. I'll try to release first beta for testing in this weekend. Only option to login will be with Get cookies.txt method.

**Comment by Dis90** [comment]
Because I don't have account to dplus india can you go to url https://ap2-prod-direct.discoveryplus.in/cms/routes/liked-videos?include=default and https://ap2-prod-direct.discoveryplus.in/cms/routes/watch-later?include=default
Save content of both to own .txt and paste here. Thanks.

**Comment by rose-will** [comment]
Link 1 responds with this
{
  "errors" : [ {
    "status" : "400",
    "code" : "invalid.token",
    "id" : "sEZap190Ci",
    "detail" : "Token invalid"
  } ]
}
Link 2 responds with this
{
  "errors" : [ {
    "status" : "400",
    "code" : "invalid.token",
    "id" : "BIf1jlDnna",
    "detail" : "Token invalid"
  } ]
}

Let me know if I'm doing something wrong as the I'm not familiar with this json

**Comment by rose-will** [comment]
[own.txt](https://github.com/Dis90/plugin.video.discoveryplus/files/5976092/own.txt)
I've attached the file of aforementioned link and JSON packets hope it helps

**Comment by Dis90** [comment]
Do you have something in favorites? Because I don't see any favorites in those files.

**Comment by rose-will** [comment]
![Capture](https://user-images.githubusercontent.com/20745463/107856634-7c312780-6e4f-11eb-848e-3f3aa9a8eb44.PNG)
![Capture2](https://user-images.githubusercontent.com/20745463/107856636-7dfaeb00-6e4f-11eb-89f3-d2806cd97846.PNG)
![Capture3](https://user-images.githubusercontent.com/20745463/107856630-7a676400-6e4f-11eb-9c07-a39389254039.jpg)

Yes, I've not added anything to favourites yet.

**Comment by Dis90** [comment]
Can you add something to your favorites so I can see what data looks like? Is watchlist just list of what you have watched?

**Comment by Dis90** [comment]
Can you try with https://github.com/Dis90/plugin.video.discoveryplus/tree/dplus_india
Kodi 19 (Matrix) only and login is not supported by addon so you have to use Get cookies.txt method (described in README).

**Comment by rose-will** [comment]
sorry for the delay in response.I'm using kodi 18.9(leia). 
[own_v2.txt](https://github.com/Dis90/plugin.video.discoveryplus/files/5977999/own_v2.txt)
watchlist is an option to add videos just like favorites.i've added a video as sample and the data file too.
Q1. Sorry but your previous comment with ..../dplus_india path is it path for zip addon in file manager option of kodi or something else.i'm confused? 
Q2. do i install the get cookies.txt addon log in in chrome and export the txt file to addon setting cookies.txt path?

**Comment by Dis90** [comment]
Q1: Click Code -> Download ZIP and install that zip in Kodi
Q2: Yes.

**Comment by rose-will** [comment]
Dis90, Thanks for your efforts. It is working now with cookies.txt method. With all subtitles and audio language support.
I'm only having issues with favourite and watchlist as they still show empty after adding some videos on them.
And it works under 'discovery.in ' might have to put that in readme.md

**Comment by Dis90** [comment]
Thanks for testing. It is hard to code function that I can't really test (favourites). Can you go to your favourites and make HAR dump? Instructions https://support.securly.com/hc/en-us/articles/213891368-What-is-a-Chrome-Network-Dump-HAR-and-where-do-I-find-it-
Remove your cookies from file before uploading it.

I will add discoveryplus.in to README after it is completely working.

**Comment by rose-will** [comment]
[www.discoveryplus.in.har.zip](https://github.com/Dis90/plugin.video.discoveryplus/files/5982372/www.discoveryplus.in.har.zip)
I've added the HAR file as requested. 
>Went to the application section inside the developer option and cleared cookies don't know if it is the right way to do it.
>Visited favorites and watchlist from home and made the HAR.
> I found that there are two major sections called Kids access and all access(opens with a 4 Digit pin) which have their own unique Favorites and watchlist. Added the video for clarity
https://drive.google.com/file/d/1WiYmnyP38VZ1TWApI3qZTXSYqtTq3h64/view?usp=sharing

**Comment by Dis90** [comment]
This is harder than I thought. Can you go to url https://ap2-prod-direct.discoveryplus.in/users/me/favorites?include=default and check if your favorite shows are listed there. Check also url https://ap2-prod-direct.discoveryplus.in/content/shows/?decorators=isFavorite&include=images,contentPackages&filter[isFavorite]=true&page[size]=10&page[number]=1

**Comment by rose-will** [comment]
[Check.txt](https://github.com/Dis90/plugin.video.discoveryplus/files/5985154/Check.txt)
Yes, my favorite show is listed here & checked both URL. return JSON is in txt file.

**Comment by Dis90** [comment]
Thanks. Can you add something to your watchlist episodes and go to this url https://ap2-prod-direct.discoveryplus.in/users/me/playlists/dplus-watchlist-videos?include=video

**Comment by rose-will** [comment]
[own_v3.txt](https://github.com/Dis90/plugin.video.discoveryplus/files/5993071/own_v3.txt)

**Comment by Dis90** [comment]
Okay it seems like it is only basic list of watchlist videos. Can you check this url https://ap2-prod-direct.discoveryplus.in/content/videos?decorators=viewingHistory,isFavorite&include=images,contentPackages&filter[playlist]=dplus-watchlist-videos&page[size]=100&page[number]=1

**Comment by rose-will** [comment]
[Uploading own_V4.txt…]()

**Comment by Dis90** [comment]
Please try now with https://github.com/Dis90/plugin.video.discoveryplus/tree/dplus_india
Does favorites and watchlist work correctly?

**Comment by rose-will** [comment]
Yeah, It works correctly( Favourites and watchlist) .Kiitos paljon ( thank you so much) for making this.

![Kodi 20-02-2021 8 22 30 PM](https://user-images.githubusercontent.com/20745463/108599975-4b567280-73ba-11eb-8b8e-f4c3e3ac5b91.png)
![Kodi 20-02-2021 8 30 52 PM](https://user-images.githubusercontent.com/20745463/108600043-a7b99200-73ba-11eb-8287-6d1a090960fa.png)
![Kodi 20-02-2021 8 31 17 PM](https://user-images.githubusercontent.com/20745463/108600045-a9835580-73ba-11eb-9957-850b35dda019.png)

**Comment by Dis90** [comment]
Good. Thank you for your help :)

**Comment by Dis90** [comment]
Support added.

**Comment by nikhilk0** [comment]
Thanks for adding the support for Indian region. Everything works perfectly fine except the live channels. This is the snippet of the log file when I play any live channel.

> 2021-04-11 16:20:30.592 T:13080    INFO <general>: initializing python engine.
2021-04-11 16:20:31.376 T:13080 WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
2021-04-11 16:20:32.078 T:13080    INFO <general>: Skipped 1 duplicate messages..
2021-04-11 16:20:32.078 T:13080    INFO <general>: CPythonInvoker(23, C:\Users\nikhil\AppData\Roaming\Kodi\addons\plugin.video.discoveryplus\addon.py): script successfully run
2021-04-11 16:20:32.402 T:13080    INFO <general>: Python interpreter stopped
2021-04-11 16:20:33.692 T:3056     INFO <general>: initializing python engine.
2021-04-11 16:20:34.488 T:3056  WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
2021-04-11 16:20:35.252 T:3056    ERROR <general>: Skipped 1 duplicate messages..
2021-04-11 16:20:35.252 T:3056    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'schemes'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\nikhil\AppData\Roaming\Kodi\addons\plugin.video.discoveryplus\addon.py", line 2901, in <module>
                                                       router(sys.argv[2][1:])
                                                     File "C:\Users\nikhil\AppData\Roaming\Kodi\addons\plugin.video.discoveryplus\addon.py", line 2878, in router
                                                       helper.play_item(params['video_id'], params['video_type'])
                                                     File "C:\Users\nikhil\AppData\Roaming\Kodi\addons\plugin.video.discoveryplus\resources\lib\kodihelper.py", line 243, in play_item
                                                       stream = self.d.get_stream(video_id, video_type)
                                                     File "C:\Users\nikhil\AppData\Roaming\Kodi\addons\plugin.video.discoveryplus\resources\lib\dplay.py", line 848, in get_stream
                                                       if data_dict['attributes']['protection']['schemes'].get('widevine'):
                                                   KeyError: 'schemes'
                                                   -->End of Python script error report<--
                                                   2021-04-11 16:20:35.555 T:3056     INFO <general>: Python interpreter stopped
2021-04-11 16:20:35.595 T:15212   ERROR <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.discoveryplus/?action=play&video_id=95&video_type=channel]

I have only tested this on 2 windows machines and faced the same issue. I hope you can fix this.

**Comment by Dis90** [comment]
@nikhilk0 Please open new issue on Github and post full debug log. Log file can contain personal data so please edit those from log.
