### ISSUE TITLE
subtitle option

### ISSUE THREAD

**Issue by dsgithub2k** [Dis90/plugin.video.discoveryplus#37]
Hi there,
installed and watching Disc+ on Kodi is awesome by the way thank for that. Any chance to add subtitle on the episodes?  on the original app for android theres an option for captions. 

Again thx for allowing this to happen.

**Comment by Dis90** [comment]
Which country version you are using? Subtitles should work at least in european countries.

**Comment by dsgithub2k** [comment]
USA

**Comment by Dis90** [comment]
Okay. Do you have Inputstream Adaptive enabled in discovery+ add-on settings? If it is disabled then subtitles won't work. If you have ISA enabled then it is probably something different in USA D+ vs. Europe.

Can you go to discovery+ on Chrome and open developer tools and from network tab while video is playing find file named videoPlaybackInfo. Open it in new tab and find line "type" : "hls" under that line should be url to m3u8 file. Open that url and save content from it to .txt and upload here.

**Comment by dsgithub2k** [comment]
Yes, the Enable UHD (experimental) is enabled as well the  ISA. Also the max res I'm getting out of the videos is 1088x612. My device is the latest Nvidia Shield Pro

**Comment by dsgithub2k** [comment]
some episodes 960x540

**Comment by Dis90** [comment]
Resolution depends on video. Not all videos are 4k or even 1080p. Try disable "Enable UHD (experimental)" option if that doesn't work then I need m3u8 file.

**Comment by Dis90** [comment]
@dsgithub2k Are you still experiencing problems with subtitles? I opened new issue https://github.com/Dis90/plugin.video.discoveryplus/issues/73
