### ISSUE TITLE
[discoveryplus.in] Audio stream (language) not changing properly on Live channels 

### ISSUE THREAD

**Issue by nikhilk0** [Dis90/plugin.video.discoveryplus#43]
All other content is working on Indian discovery plus. But the live channels are not playable.

**Comment by Dis90** [comment]
Try with this https://github.com/Dis90/plugin.video.discoveryplus/tree/matrix click Code -> Download ZIP
Hopefully it fixes problem. Please note that if you are using my repository when you install add-on outside repository you are no longer getting updates automatically.

**Comment by nikhilk0** [comment]
Thanks for the quick fix. Live channels are now working properly with all available audio streams.

**Comment by nikhilk0** [comment]
I have couple of other annoyance with the addon. Although those are not related to live channels, I'll still mention it here. If you want me open another issue for them, please tell me. The home section of the addon only shows bottom 4 sections from the home section of the website. Maybe, those 4 sections are static sections. This might be happening because of the cookies method Indian users have to use. But I'm not sure about it.
Also, there is a separate kids section on the website which isn't shown in addon.

**Comment by Dis90** [comment]
Please open new issue :) It's hard to develop Indian version because it's little bit different than EU version and I don't have account to it.

**Comment by nikhilk0** [comment]
Hey, this is regarding live tv. As I said in my previous comment, the live channels are playing, and all the available audio streams are listed. But that time I had tested on mute. The audio streams are not working properly. When I change the audio stream to another language, the audio stops playing instead of switching to that language.
Here's the debug log
[kodi.log](https://github.com/Dis90/plugin.video.discoveryplus/files/6302778/kodi.log)

**Comment by Dis90** [comment]
All that is handled by Kodi/InputStream Adaptive. Unfortenatly I don't know how to fix it and finnish d+ doesn't have multiple audio streams so I can't debug it.
What if you start video from beginning after changing audio stream?

**Comment by nikhilk0** [comment]
> What if you start video from beginning after changing audio stream?

Yep. It's working that way. 
Play the channel. Change the audio language as per requirement. Stop the channel. And play again. The channel plays in the language selected before stopping the stream earlier.

This audio issue doesn't occur when playing normal episodes. Many episodes also have multiple audio streams, but they change without any issue.

**Comment by nikhilk0** [comment]
I've opened an [issue](https://github.com/xbmc/inputstream.adaptive/issues/648#issue-857567246) on ISA repo and it has been labelled as a bug. Hope it gets fixed in the near future.

**Comment by nikhilk0** [comment]
The issue is solved with ISA 2.6.16 Matrix.
