### ISSUE TITLE
Some sections from the website are missing

### ISSUE THREAD

**Issue by nikhilk0** [Dis90/plugin.video.discoveryplus#44]
On discoveryplus.in, the home section has way more sections than which are present in the addon. 

This is the web capture of the whole home page. (All these sections didn't appear on immediately after loading. Had to scroll couple of times to get all the sections)
![Web capture_13-4-2021_125152_www discoveryplus in](https://user-images.githubusercontent.com/45728234/114513354-b9e7dc00-9c57-11eb-847c-141708503315.jpeg)

This is what is visible in the home section of the addon (only bottom 4 sections from the webpage)
![Screenshot (77)](https://user-images.githubusercontent.com/45728234/114513526-e69bf380-9c57-11eb-9789-d312119013f0.png)

Also, kids section is missing.
![Screenshot (78)](https://user-images.githubusercontent.com/45728234/114513714-1cd97300-9c58-11eb-86bd-4c001af7e64a.png)

**Comment by Dis90** [comment]
I can't fix this because d+ India is geoblocked and currently I don't have VPN. But if some skilled coder have spare time, PR's are welcome.

**Comment by nikhilk0** [comment]
https://paste.kodi.tv/ocaweciyix   -v3
https://paste.kodi.tv/zuxujocuca  -v2
https://paste.kodi.tv/vorapugafi   -last url

**Comment by Dis90** [comment]
It looks like Kids category is not in same menu as other links so I have to find menu which contains all links or hardcode Kids category to menu like Watchlist and favorites. Without knowing actual url to Kids category data can you try to add this to addon.py between lines 25 and 26

`helper.add_item('Kids', params={'action': 'list_page', 'page_path': '/kids'})`

**Comment by nikhilk0** [comment]
I added your line to addon.py, but kodi returned error. So I opened developer options in kids section and below url seems to be for that section
https://ap2-prod-direct.discoveryplus.in/cms/routes/kids/home?include=default&decorators=isFavorite,viewingHistory 

https://paste.kodi.tv/pipiyohira - json for the above url

See if this help

**Comment by Dis90** [comment]
Try with:
`helper.add_item('Kids', params={'action': 'list_page', 'page_path': '/kids/home'})`

**Comment by nikhilk0** [comment]
This is working.
![image](https://user-images.githubusercontent.com/45728234/114564450-f33b3e80-9c8d-11eb-8683-208980c00ae6.png)
![image](https://user-images.githubusercontent.com/45728234/114563006-a6a33380-9c8c-11eb-85e8-d70c087cb3b5.png)
Only problem is first 2 options are empty. These are those options on the webpage.
![image](https://user-images.githubusercontent.com/45728234/114562868-86737480-9c8c-11eb-9952-64d1acc26b5c.png)

**Comment by nikhilk0** [comment]
For home section, this is structure for the categories

https://ap2-prod-direct.discoveryplus.in/cms/collections/home-continue-watching?include=default&decorators=viewingHistory,isFavorite
https://ap2-prod-direct.discoveryplus.in/cms/collections/new-shows-this-month?include=default&decorators=viewingHistory,isFavorite
https://ap2-prod-direct.discoveryplus.in/cms/collections/pwa-taxonomy-categories?include=default&decorators=viewingHistory,isFavorite
https://ap2-prod-direct.discoveryplus.in/cms/collections/pwa-superstars-collection?include=default&decorators=viewingHistory,isFavorite

There are more such urls for each of the categories. Refer to the SS in 1st comment. 
I don't know whether these are helpful or not. Also, tell me if you want output of any of these links.

**Comment by Dis90** [comment]
Superheroes category should work with this https://github.com/Dis90/plugin.video.discoveryplus/tree/dplus_in_fixes

**Comment by nikhilk0** [comment]
Even carousel showcase is working this.

**Comment by Dis90** [comment]
Good to know. Can you post output of https://ap2-prod-direct.discoveryplus.in/cms/configs/client-config-pwa and https://ap2-prod-direct.discoveryplus.in/cms/routes/home?include=default

I'm trying to find file where those home-continue-watching etc is listed.

**Comment by nikhilk0** [comment]
https://paste.kodi.tv/xeloberede - config
https://paste.kodi.tv/inukaqusej - home

**Comment by Dis90** [comment]
Thanks. Then https://ap2-prod-direct.discoveryplus.in/cms/collections/new-shows-this-month?include=default&decorators=viewingHistory,isFavorite

**Comment by nikhilk0** [comment]
https://paste.kodi.tv/oliyobinag

**Comment by Dis90** [comment]
I don't understand why it doesn't display those. Can you try edit lines 542-545 from addon.py to `collection = helper.d.get_collections(collection_id=home_collection)['data']` so basically just delete try and expect. If you get error post debug log.

**Comment by nikhilk0** [comment]
Got error. 
[kodi.log](https://github.com/Dis90/plugin.video.discoveryplus/files/6305752/kodi.log)

**Comment by Dis90** [comment]
Now I know what is causing the problem. Try https://github.com/Dis90/plugin.video.discoveryplus/tree/dplus_in_fixes

**Comment by nikhilk0** [comment]
Its working!! Thanks for these quick fixes and improvements.

**Comment by Dis90** [comment]
Thank you for help :) I will make new release with all fixes.
