### ISSUE TITLE
no sound in discovery +

### ISSUE THREAD

**Issue by cabban** [Dis90/plugin.video.discoveryplus#48]
suddenly swedish discovery+  have lost sound 
![no sound](https://user-images.githubusercontent.com/19514493/116811325-00d73c00-ab49-11eb-866c-befb69dab5c0.jpg)
tested and som e addons works but not some addons not working any tips gladly would appreciated , 18.9 kodi verison windows 
i have sound but not here attachhed sc is sound info 0 0 0 :/ @Dis90

**Comment by Dis90** [comment]
Have you tested same videos on discovery+ website? Is audio available there? What is your Inputstream Adaptive version?

**Comment by cabban** [comment]
Yes video is available
With sound on Webpage
2.4.7 cheers
söndag 2 maj 2021 skrev Dis90 ***@***.***>:

**Comment by Dis90** [comment]
Is audio missing from all videos or just some videos? You mentioned other addons, if audio is missing from other addons too then it is probably something wrong with your system.

**Comment by cabban** [comment]
> Is audio missing from all videos or just some videos? You mentioned other addons, if audio is missing from other addons too then it is probably something wrong with your system.

yes i thought about that but its working all over computer, its working in all video addons except retrospect and discovery + dont know 
:(

**Comment by Dis90** [comment]
I will keep this open for a couple of days and if nobody else reports similar issues I close this issue.

**Comment by cabban** [comment]
I reinstall the whole kodi and suddenly all sound come back so close it you
can now😀thank u

måndag 3 maj 2021 skrev Dis90 ***@***.***>:
