### ISSUE TITLE
Listings are limited to 100 items

### ISSUE THREAD

**Issue by nickehallgren** [Dis90/plugin.video.discoveryplus#55]
I would like to start to thank you for this plugin and all the work you have put into it!

I'm running the plugin on CoreElec 19.2-Matrix_rc2 (latest stable) but I had the same problem on legacy 9.2.7 (18.x).

When I go to for example Channels->Discovery->Programs (Kanavat->Discovery->Ohjelmat), I shows me only the 100 first programmes (100) Items - Page (8/8). The same happens on all listings that have more than 100 programmes.

Why is it only showing 100, in the plugin settings the maximum Results per Page is set to 100. I tried to chage it to 10 but it doesn't seem to make any difference in the "main" listings. But if I go to for example Programmes-> The Big Bang Theory->Season 12 it shows me the "Next Page" after 10 episodes.

Thanks in advance!
Nicke

**Comment by Dis90** [comment]
Website seems to be updated not to show categories Ohjelmat and Uusimmat videot in most channel pages instead it will list all programs. But I will continue use old method with little update which should fix this issue. Expect new release of add-on today.

**Comment by Dis90** [comment]
Issue should be fixed in master and Leia branches but I will not make new release of add-on until I have done little bit code cleanup.

**Comment by nickehallgren** [comment]
Wow, very fast. Thank you it works perfectly on Channels->Discovery->Programs.

This is not so importand (now when it lists all the programmes) but Under Programes (Ohjelmat) were all the programs are found the sorting is not alphabetic. I tried to change Sort by: Default-> Name but it only sorts the visible list...

Thanks again!

**Comment by Dis90** [comment]
> This is not so importand (now when it lists all the programmes) but Under Programes (Ohjelmat) were all the programs are found the sorting is not alphabetic. I tried to change Sort by: Default-> Name but it only sorts the visible list...

Listing is in same order as https://www.discoveryplus.fi/ohjelmat (Suosituimmat ohjelmat) that is why it is not in alphabetical order. And you are right sorting in Kodi affects only in visible items.

**Comment by nickehallgren** [comment]
Had to open the Discovery+ app on the tablet (rarely using it since I started using Kodi to watch on the TV) and you are right. Thank you!
