### ISSUE TITLE
Extend plugin for eurosportplayer users

### ISSUE THREAD

**Issue by maxbambi** [Dis90/plugin.video.discoveryplus#56]
Hi, I have got a eurosport player account (not all discovery plus services) .
By adding these lines in dplay.py:
```
        if self.site_url == 'eurosportplayer.com': 
            self.api_url = 'https://eu3-prod-direct.eurosportplayer.com'
            self.realm = 'eurosport'
            self.site_headers = {'x-disco-params': 'realm=eurosport' , 'x-disco-client':'WEB:UNKNOWN:esplayer:prod'}

``` 

I can use your plugin to see live streaming of eurosport player, with my account and some cookies copied from my web browser.

Schedule section isn't working: maybe some keys are in different position in JSON responses.

Could you add this possibility to your plugin?

**Comment by Dis90** [comment]
There's separate addon for Eurosport player. Have you tried that?
https://forum.kodi.tv/showthread.php?tid=205551
https://github.com/sterd71/plugin.video.eurosporton

**Comment by maxbambi** [comment]
@Dis90 
Yes, I have tried it, but it is not perfect... 
Some thing works with yours (i.e. I can see current streaming of linear channels E1 e E2), with eurosporton I have sport lists

According to the idea to fix one of them, your plugin seems more recent and updated

**Comment by Dis90** [comment]
Maybe not worth it because it seems like they are moving Eurosport stuff to Discovery+
https://www.sportspromedia.com/news/discovery-plus-eurosports-player-tv-rights-strategy-andrew-georgiou

There is active development going on plugin.video.eurosporton. So maybe better make bug report there for non working stuff :)
