### ISSUE TITLE
Channels on Discovery+ Italy no longer loading/working

### ISSUE THREAD

**Issue by calypsodeep** [Dis90/plugin.video.discoveryplus#57]
Everything was fine until yesterday 01/09/2021 then they stopped working.

**Comment by Dis90** [comment]
You probable have too old Inputstream Adaptive addon. Can you check version you have? I tested Italian d+ channels and those plays fine.

**Comment by calypsodeep** [comment]
I think I am using the latest version on Inputstream Adaptive (2.4.8.1.)
I have however managed to solve the issue following the steps in that forum.

Thank you Sir 😊
