### ISSUE TITLE
Error installing on Kodi 19

### ISSUE THREAD

**Issue by fra87** [Dis90/plugin.video.discoveryplus#59]
Hi
I just upgraded Kodi to v19, and the plugin (which was working flawlessly) was disabled.

I tried to enable it, but it said the plugin was not compatible with v19
I tried using the repository to reinstall it, but without any luck (no versions were available, I just got the option to install the repo v1.0.1 instead of v1.0.0)
I tried downloading the 1.5.23 version, but it does not install (Error is that dependency from xbmc.python v2.24 may be not fulfilled)

What can I do?

Best regards

**Comment by Dis90** [comment]
I don't know why repository is not working for you. Double check you have installed matrix version of repository https://github.com/Dis90/repository.dis90/raw/matrix/repo/repository.dis90-1.0.1.zip

Sometimes it can take little time to Kodi display contents of repository. You can also install discovery plus manually from https://github.com/Dis90/plugin.video.discoveryplus/releases but then automatic updates from repository doesn't work.

**Comment by fra87** [comment]
> I don't know why repository is not working for you. Double check you have installed matrix version of repository https://github.com/Dis90/repository.dis90/raw/matrix/repo/repository.dis90-1.0.1.zip
> 
> Sometimes it can take little time to Kodi display contents of repository. You can also install discovery plus manually from https://github.com/Dis90/plugin.video.discoveryplus/releases but then automatic updates from repository doesn't work.

Honestly I don't know what happened. I tried to download the repo again and install, and this time the video addon folder was present.
Maybe I shall have waited for some more time.

Now it works correctly
Thank you
