### ISSUE TITLE
error accessing bakeoff in italian version

### ISSUE THREAD

**Issue by red5454** [Dis90/plugin.video.discoveryplus#60]
when trying to get bake off Iiget an error message .I enclose the log  page as Ihope will be useful.thanks a lot for your great work
massimo
![Screenshot_2021-09-14-07-10-22-029](https://user-images.githubusercontent.com/57556567/133199393-d7447d87-f41b-47f2-945f-f652a9c6ca5b.jpeg)

**Comment by Dis90** [comment]
Thanks for report. Fixed in version 1.5.24.
