### ISSUE TITLE
Tracking watched date/time etc.

### ISSUE THREAD

**Issue by iPFT** [Dis90/plugin.video.discoveryplus#61]
Hi great plugin

Quick question as I can't find any formal documentation for the API and I know this is an unofficial plugin - is there anything in the json files that can determine the watch status of a user - e.g. something as basic as netflix viewing activity which shows date/time watched and title https://www.netflix.com/viewingactivity

https://disco-api.discoveryplus.co.uk/users/me/allData shows the id and progress, but would be great to know about date/time/title so things can be scrobbled into something like trakt/imdb etc.

Thanks

**Comment by Dis90** [comment]
Yep. If you run issues with page not listing all watched videos then you probably need to add &page[size]=100&page[number]=1 and change page number to 2 to get next 100 videos.
