### ISSUE TITLE
Playback on issues on discoverplus.no for new programs after Dec 2021

### ISSUE THREAD

**Issue by Likkie** [Dis90/plugin.video.discoveryplus#64]
When using discoveryplus.no for programs/episodes dated after Dec 01 2021 playback back is choppy and picture quality poor.  If I bring up an overlay that shows the cache usage I see that it runs out all the time and playback stops.  Doesn't seem to matter what video quality I choose.

If I select and older program/episode playback is normal and the cache stays at 95% to 100% all the time even if I playback at higher res than normal. I usually choose 540P streams.

I'm not sure what other information to gather to assist but it seems like D+.no is doing something different since 1st December.

**Comment by Dis90** [comment]
Have you tried to play same videos from D+ website? It can be something related to upcoming new website and app or just coincidence.

Older Kodi versions doesn't have proper buffer but upcoming Kodi 20 has. If possible maybe try out playback with Kodi 20.

**Comment by Likkie** [comment]
I will check their app out after they have finished their changes...

I never really used it before because it always plays back in a lower quality mode for me.  I can choose the video quality with this Kodi add-on.

I've been using this add-on for over a year and never had any problem until now. It's better that their app :)

**Comment by Dis90** [comment]
@Likkie Have you tried playback now after recent updates?

**Comment by Likkie** [comment]
Since the update to their services I can no longer log in to their website.  So I can't generate a bnew cookie. :(

However, their app is working quite nicely now.
