### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by crak3rjack** [Dis90/plugin.video.discoveryplus#65]
@Dis90 Now that login is gone could it possible to add the cookie (copy & paste) into the settings of the addon by it self like when you put email instead of the cookies location.

**Comment by Dis90** [comment]
I will investigate it. Is there some benefits to do it? It still requires user to look cookie from browser.

**Comment by crak3rjack** [comment]
@Dis90 It's easier and convenient for people that have multiple set up... example I make the login in my PC then I copy the userdata folder and paste it in my Android TV BOX or phone.

**Comment by Dis90** [comment]
It is now possible to set cookie from add-on settings. See instructions in README.
