### ISSUE TITLE
Can't choose profile

### ISSUE THREAD

**Issue by crak3rjack** [Dis90/plugin.video.discoveryplus#66]
@Dis90 tahnks for the request i got logged in whit the cookie from the setting but i can't choose any of my profiles.
https://pastebin.com/6M3rhrCK

**Comment by Dis90** [comment]
Please upload full debug log but remember remove your personal details from it (email etc.)

**Comment by Dis90** [comment]
Actually that is normal error which comes after selecting profile. Go back to main menu and back to profiles and check if profile is changed.
