### ISSUE TITLE
Error loading cookies.txt?

### ISSUE THREAD

**Issue by lockyt** [Dis90/plugin.video.discoveryplus#68]
Hi I am getting the following error when I go to run discovery+ addon.  I was working fine yesterday.

```
2021-12-19 01:25:36.002 T:1469006720   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IOError'>
                                            Error Contents: [Errno 2] No such file or directory: '/storage/.kodi/userdata/addon_data/plugin.video.discoveryplus/realm_config'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.discoveryplus/addon.py", line 14, in <module>
                                                helper = KodiHelper(base_url, handle)
                                              File "/storage/.kodi/addons/plugin.video.discoveryplus/resources/lib/kodihelper.py", line 37, in __init__
                                                self.get_setting('cookiestxt_file'), self.get_setting('cookie'), self.get_setting('us_uhd'))
                                              File "/storage/.kodi/addons/plugin.video.discoveryplus/resources/lib/dplay.py", line 48, in __init__
                                                realm_config    = self.load_realm_config()
                                              File "/storage/.kodi/addons/plugin.video.discoveryplus/resources/lib/dplay.py", line 189, in load_realm_config
                                                f = open(config_file, "r")
                                            IOError: [Errno 2] No such file or directory: '/storage/.kodi/userdata/addon_data/plugin.video.discoveryplus/realm_config'
                                            -->End of Python script error report<--
```

I have checked the cookies.txt and it is there and permissions seem fine.  I have also created a new cookies.txt (after a new login into the website on chrome) and put that in place, but still no dice.  I also installed a brand new copy of LibreELEC and newly installed discovery+ add-on but still same error. (I used the same version of both LibreElec and Discovery+ from my downloads that I originally used).

Any ideas on what I am doing wrong?

**Comment by Dis90** [comment]
Try restart Kodi. It reports that realm_config file is missing and add-on should download it on startup of Kodi. But atleast when add-on is updated it doesn’t run service for downloading realm config. I need to fix that. Please let me know if that fixes the problem.

**Comment by lockyt** [comment]
Yes have tried rebooting Kodi a few times - makes no difference.  Also tried removing discovery+ and your repository and added all back - same problem.

What is realm_config part of - maybe I can add that dependency manually?

**Comment by lockyt** [comment]
I had cookies.txt on a USB stick and that is where it reads it from - worked fine but this morning I booted and tried running discovery+ without it plugged in - maybe that is what caused the problem?

USB plugged in now.  Have also tried copying it to the filesystem and pointing discovery+ to there - same issue however.

**Comment by Dis90** [comment]
It is hard to explain what exactly is needed but if you know how Chrome devtools work you can open discoveryplus.com and look for url https://prod-realmservice.mercury.dnitv.com/realm-config/ and save contents of that to addon_data/plugin.video.discoveryplus/realm_config. You can’t go directly to that address because it is missing your country specific url to d+. Well if you are from USA it is easy just add www.discoveryplus.com to end of url.

**Comment by Dis90** [comment]
Actually main problem can be missing settings folder. Do you have folder addon_data/plugin.video.discoveryplus? Of not try to create it and hopefully that fixes the problem.

**Comment by lockyt** [comment]
Just checked and that directory exists - it has a file called settings.xml in there.

**Comment by lockyt** [comment]
by the way, I did a spot check on the files that are being referenced in the error - all I checked so far are there

**Comment by lockyt** [comment]
Although I can't see /storage/.kodi/userdata/addon_data/plugin.video.discoveryplus/realm_config

**Comment by lockyt** [comment]
> It is hard to explain what exactly is needed but if you know how Chrome devtools work you can open discoveryplus.com and look for url https://prod-realmservice.mercury.dnitv.com/realm-config/ and save contents of that to addon_data/plugin.video.discoveryplus/realm_config. You can’t go directly to that address because it is missing your country specific url to d+. Well if you are from USA it is easy just add [www.discoveryplus.com](http://www.discoveryplus.com) to end of url.

I'm in Australia.  I will see if I can find the url you mention - any particular section of Dev tools?

**Comment by Dis90** [comment]
Network tab and refresh page after opening it

**Comment by Dis90** [comment]
I just tried to go Australian d+ and website says:
Soon…But Not Quite Yet
discovery+ is not yet available in this location.

We can’t wait to bring discovery+ to your part of the world!

So are you using VPN or what is going on?

**Comment by lockyt** [comment]
Sorry yes, using a VPN - should have explained that.  VPN through to UK.

**Comment by lockyt** [comment]
Being a bit dim.

**Comment by lockyt** [comment]
Ok found that section - which bit do I save to realm_config?

**Comment by lockyt** [comment]
Just the full URL with the bit on the end?

**Comment by lockyt** [comment]
Ok so I guess I paste that URL into the browser and copy the response into realm_config in that directory?  If so, just tried that and didn't work.

**Comment by Dis90** [comment]
Can you post contents of realm config? I'm starting to think this is something to do with VPN.

**Comment by lockyt** [comment]
{"environment":"prod","authDomain":"auth.discoveryplus.com/gb","domain":"eu1-prod-direct.discoveryplus.com","brandId":"dplus","realm":"dplay","pathRegex":"www\\.discoveryplus\\.com\\/gb($|\\/.*)","mainTerritoryCode":"gb","siteLookupKey":"dplus_uk"}

**Comment by lockyt** [comment]
I think I got it working - got past the error - realised I create realm_config in `/storage/.kodi/addons/plugin.video.discoveryplus` not `/storage/.kodi/userdata/addon_data/plugin.video.discoveryplus/realm_config`

I have fixed now - but it asked to install waveline or something like that to watch the video file.  Asked if I wanted to install where I said yes.  It then said I need chrome OS recovery image to work which it is now doing but it is 1gb in size?  I suspect that isn't needed?

**Comment by lockyt** [comment]
So waiting for chrome OS recovery image to download before I can see if a video plays

**Comment by Dis90** [comment]
You need widevine in order to play drm protected videos. So yes it is needed.
realm_config should be in addon_data/plugin.video.discoveryplus but I don't know if LibreELEC is doing something different.

**Comment by lockyt** [comment]
It was wideline sorry.  It was what needed chrome os recovery image.

**Comment by lockyt** [comment]
And yes added to add-on_data/plugin.video.discoveryplus

**Comment by Dis90** [comment]
So everything is working now?

**Comment by lockyt** [comment]
Had to go off and do something else but I think so.  Let you know if any problems.  Thanks for your help!

**Comment by tommyp-vr4** [comment]
Things seem a little funny here too.  The addon isn't working for me today.  Where exactly did you put that realm_config?
Did you create a file called "realm_config" inside the /storage/.kodi/userdata/addon_data/plugin.video.discoveryplus folder?  
Or do you need some arbitrary named file and some arbitrary file extension in a folder named "/storage/.kodi/userdata/addon_data/plugin.video.discoveryplus/realm_config"

**Comment by Dis90** [comment]
Are you using latest version (1.6.6)? It should be fixed in it. If yes please post full debug log so I can investigate this issue.

**Comment by tommyp-vr4** [comment]
Thank Di90.  Yes, I am using 1.6.6.  I enabled the full logging, rebooted, ran the addon (and get an error).  Then I shopped the logging.  I think the mrs said she saw a prob yesterday or the day before too.  If it matters, the same computer can play via a webbrowser (chromium).  Let me know if you need more info.  Thanks!
[kodi.log](https://github.com/Dis90/plugin.video.discoveryplus/files/7741525/kodi.log)

**Comment by Dis90** [comment]
Thanks for log. I now know why this is not working. Try copy file __init__.py from /storage/.kodi/addons/plugin.video.discoveryplus/resources to /storage/.kodi/addons/plugin.video.discoveryplus/resources/services

Let me know if that fixes problem.

**Comment by tommyp-vr4** [comment]
Bingo!  That did the trick.  All is back to normal!  Works like a champ!  Thanks for the fix and for doing what you do!
