### ISSUE TITLE
realmservice throws PythonToCppException since 19-12

### ISSUE THREAD

**Issue by dave4477** [Dis90/plugin.video.discoveryplus#69]
Hi, to start, great work on the plugin, I have enjoyed it many hours and run it on 2 raspberry Pi KODI systems.
Since 19th of December 2021 on both my Kodi devices the following error started to occur, preventing me to use the plugin. Both devices are running kodi leia.
Both devices give me the same error in the log files:

2021-12-19 19:58:30.033 T:2803151680   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named services.realmservice
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.discoveryplus/services.py", line 5, in <module>
                                                import resources.services.realmservice as realmservice
                                            ImportError: No module named services.realmservice
                                            -->End of Python script error report<--
                                            
                                            
If I start the plugin, it throws the default "Discovery+ error, check log files for more information" and does not show anything.
Kind regards

**Comment by Dis90** [comment]
This is now fixed in version 1.6.7. Can you check if it now works?

**Comment by dave4477** [comment]
Hi! Thanks for getting back to me. I have downloaded and installed 1.6.7 and the issue is now resolved. 
Many thanks!
