### ISSUE TITLE
Problems with android 11

### ISSUE THREAD

**Issue by MaxmaxOk** [Dis90/plugin.video.discoveryplus#72]
Hi sorry but the addon doesn't work with android 11,after looking in the kodi log seems like a permission problem in "data" folder

**Comment by Dis90** [comment]
Can you post debug log? I don't have any Android devices so I can't test addon on Android.

**Comment by MaxmaxOk** [comment]
Hi here's the kodi log:

[kodi.log](https://github.com/Dis90/plugin.video.discoveryplus/files/7775741/kodi.log)

**Comment by MaxmaxOk** [comment]
Hi sorry now works just fine,i reinstalled the addon and the cookie file...all works flawless ,merry christmas!
