### ISSUE TITLE
Non working subtitles

### ISSUE THREAD

**Issue by Dis90** [Dis90/plugin.video.discoveryplus#73]
If you are experiencing problems with subtitles there's two things you can try.

1. Disable "Use DRM" on add-on settings. This can break subtitles on older videos at least in D+ Finland.
2. Update to Kodi 20.

@yeahme49 can you try Kodi 20/DRM enabled on D+ USA?

Links:
https://forum.kodi.tv/showthread.php?tid=340055&pid=3076385#pid3076385
https://github.com/xbmc/inputstream.adaptive/issues/855
https://github.com/Dis90/plugin.video.discoveryplus/issues/5#issuecomment-1003420083

Edit. InputStream Adaptive version 19.0.2 fixes issues in Kodi 19 in European countries. Update to it and you can leave DRM enabled. USA users still need to set DRM disabled.

**Comment by yeahme49** [comment]
Kodi 20/DRM does not work

**Comment by Dis90** [comment]
Okay. That confirms that D+ uses different subtitle format in USA. So disabling DRM is currently only way to get subtitles work on D+ USA.

**Comment by djdirty60** [comment]
In the Netherlands, the subtitle also does not work if you have DRM Enable.

**Comment by pipo1000** [comment]
For me it only works partly when I disable DRM here in the Netherlands. When I watch a show like Vintage Voltage I only have subtitles for a few minutes, after the first 'break' in edititing (intro, leader, start of show etc.) the subtitles stops working at all. Hope you can fix this!

**Comment by Dis90** [comment]
@pipo1000 It's hard to know if it is fault in InputStream Adaptive or discovery+. Website uses DRM and I don't know does they even use DRM disabled/HLS streams in any platform. Can you test this version of InputStream Adaptive https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-857/9/artifacts/

It should fix problems with DRM enables/MPD.

**Comment by djdirty60** [comment]
> @pipo1000 It's hard to know if it is fault in InputStream Adaptive or discovery+. Website uses DRM and I don't know does they even use DRM disabled/HLS streams in any platform. Can you test this version of InputStream Adaptive https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-857/9/artifacts/
> 
> It should fix problems with DRM enabled/MPD.

It works

Thnx

**Comment by pipo1000** [comment]
> @pipo1000 It's hard to know if it is fault in InputStream Adaptive or discovery+. Website uses DRM and I don't know does they even use DRM disabled/HLS streams in any platform. Can you test this version of InputStream Adaptive https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-857/9/artifacts/
> 
> It should fix problems with DRM enabled/MPD.

I use an Amlogic 922 box with CoreElec, I do not see a package which seems to be for my box to try or am I missing something?

**Comment by Dis90** [comment]
Then you have to wait for official release or build InputStream Adaptive yourself.

When you manually install any addon example InputStream Adaptive you no longer get updates via repo. So after fix is in official InputStream Adaptive you maybe want to install it so you are getting updates.

**Comment by pipo1000** [comment]
> Then you have to wait for official release or build InputStream Adaptive yourself.

Where can I see if there is an official release of this fix so I can ask the CoreElec developers to a new version of the addon on CoreElec?

**Comment by Dis90** [comment]
Official release (19.0.2) is already out. See https://github.com/xbmc/inputstream.adaptive/tree/Matrix but I don't know about CoreElec.

**Comment by pipo1000** [comment]
Still waiting for the official CoreElec 19.4 release to try out the fix.

**Comment by atreyuhere** [comment]
Just wanted to add that i too use a aml922x (odroid) device with this brilliant addon in the Netherlands region and I don't experience the issue.
 Just checked the IA version. I do not understand why exactly, but the version is 19.0.2.1. I don't see a checkmark to indicate it linked to the CE repo source, although i definitely didn't build or install IA manually.
I have been 'dirty flashing' from 19.3 to 19.4rc2/3 and back, so i wonder if the current IA version came from this. Might be worth a shot..

**Comment by pipo1000** [comment]
I also flashed from 19.3 to 19.4 and then I hit some problems with CE 19.4 CEC and freezing and went back to 19.3. Luckily the new IA stayed and now subtitles is working on 19.3 👍
