### ISSUE TITLE
[Feature Request] IPTV Merge integration?

### ISSUE THREAD

**Issue by CHJ85** [Dis90/plugin.video.discoveryplus#76]
Hi there. I'm currently using IPTV Merge allowing me to view channels from Pluto TV, Stirr and Paramount+.
So having support for IPTV Merge would be extremely nice.
Thanks for your hard work.

**Comment by Dis90** [comment]
For my knowledge I don't need to add anything special for IPTV Merge. You can use files that IPTV Manager creates with IPTV Merge. Better ask here how to do it https://forum.kodi.tv/showthread.php?tid=340691
I haven't used IPTV Merge but I know that discovery+ add-on users uses it.

**Comment by CHJ85** [comment]
Okay thank you.
I'll look into it.
