### ISSUE TITLE
Mark as viewed

### ISSUE THREAD

**Issue by djdirty60** [Dis90/plugin.video.discoveryplus#77]
Good day,

Could there be a feature that will allow you to mark episodes or seasons as watched without watching it?  There are a number of episodes in my watch list that I want to get rid of, but some have a lot of episodes.  And to flush them now 1 by 1.

Would like to hear

**Comment by Dis90** [comment]
I actually just yesterday was thinking of adding this feature. I will do this but I can't say when :)

**Comment by djdirty60** [comment]
Oke thnx

**Comment by Dis90** [comment]
With version 1.6.13 you can now mark videos as watched or unwatched.
I didn't add support for marking complete seasons as watched or unwatched because it would make really many requests to the discovery+ server.
