### ISSUE TITLE
Remove from watching further

### ISSUE THREAD

**Issue by djdirty60** [Dis90/plugin.video.discoveryplus#78]
Good day,

Sorry for one more question, there might also be a feature to remove episodes from further viewing.  Will be nice and useful.

Thank you for all the work

**Comment by Dis90** [comment]
Do you mean removing videos from "Continue Watching" list? That is not possible.

**Comment by djdirty60** [comment]
oh ok that's a shame

**Comment by Dis90** [comment]
You can try to send a suggestion of that feature to Discovery :D If it becomes possible through websites then I can do it in an add-on.
