### ISSUE TITLE
Issue with live stream on Rpi3

### ISSUE THREAD

**Issue by JoshTheTofu** [Dis90/plugin.video.discoveryplus#79]
Hi

I recently tried to watch the Winter Olympics but I got an unbelievable amount of stuttering and it is unwatchable.

I watched the summer olympics last year on this device in HD and it worked perfectly for many days on many different channels.

I have checked and the live stream works perfectly in full HD via the app on my phone on the same network so is not a network issue.

I have also changed the InputStream Adaptive settings down to 480p and even at that resolution it is still stuttering. 

What are my next steps for debugging this issue?

Kind regards

Josh

**Comment by Dis90** [comment]
That is probably issue with used Widevine version. Check https://github.com/xbmc/inputstream.adaptive/issues/877

**Comment by JoshTheTofu** [comment]
Thank you

That is exactly what it is. I followed the instructions on that thread and installed a version of WideVine from the Slyguy repo and it works perfectly. Thanks for the help and the swift reply.

Kind regards

Josh
