### ISSUE TITLE
Can not log in

### ISSUE THREAD

**Issue by djdirty60** [Dis90/plugin.video.discoveryplus#8]
![16109031994515761428014900294303](https://user-images.githubusercontent.com/13561831/104850329-c8d82000-58ee-11eb-8bd8-798b5b2c7784.jpg)
Entered my login details but he does not log in.  How can I fix that?

**Comment by Dis90** [comment]
Nothing I can do to this at the moment. For reasons unknown discovery+ login triggers "are you human" test even on website and addon doesn't support that.

If problem doesn't go away I will add possibility to use Firefox cookies so login could done in there.

**Comment by djdirty60** [comment]
> Nothing I can do to this at the moment. For reasons unknown discovery+ login triggers "are you human" test even on website and addon doesn't support that.
> 
> If problem doesn't go away I will add possibility to use Firefox cookies so login could done in there.

I am using coreelec I don't know if that is the problem.  And I can just log in to the discoveryplus website and apps

**Comment by Dis90** [comment]
If login works in browser without seeing this, it should work also in addon.
![image](https://user-images.githubusercontent.com/1754572/104851929-8c152480-5900-11eb-85db-c33a41998834.png)

**Comment by djdirty60** [comment]
I don't have to do that in the Netherlands ...

**Comment by Dis90** [comment]
Interesting. What browser and OS you used? I tested .fi and .nl (with VPN) and both showed test. I used Chrome and Firefox on Mac OS.

**Comment by djdirty60** [comment]
Chrome on Windows 10. And on coreelec I don't have a browser

**Comment by djdirty60** [comment]
Could it be the time?  In the cookie_file it is an hour earlier than mine

**Comment by Dis90** [comment]
Do you mean cookie expire time "2021-02-16 18:51:10Z" It is month away and time is GMT 0 and it is two hours earlier here in Finland.

**Comment by djdirty60** [comment]
But which kodi do you use?  Libreelec?  Coreelec?  Kodi for Android?

**Comment by Dis90** [comment]
Mac OS for testing and developing and Ubuntu in HTPC.

**Comment by djdirty60** [comment]
The Windows version has the same problem

**Comment by djdirty60** [comment]
![16109108706504990951403651200675](https://user-images.githubusercontent.com/13561831/104853362-a3eca880-5900-11eb-9a11-3a6d82a9fe3e.jpg)

**Comment by Dis90** [comment]
I can't really do anything to fix this because for me website login shows that test so I can't look there what addon does wrong. Have to wait and see if problem goes away by itself.

**Comment by djdirty60** [comment]
Can you make a version without using that test?

**Comment by Dis90** [comment]
That test is Arkose Labs Captcha what discovery+ uses. Can not delete that. For some reason it now always displays "are you human" test so I can't look for browser what parameters is needed not to trigger that test.
Only option if website continues display test like it is now, is use Firefox's cookies so addon doesn't need to handle login.

**Comment by djdirty60** [comment]
If possible, please

**Comment by Dis90** [comment]
It is now possible to export cookies from Chrome. You can use https://chrome.google.com/webstore/detail/get-cookiestxt/bgaddhkoddajcdgocldbbfleckgcbcid to export them. From addon settings specify location of cookies.txt.

**Comment by djdirty60** [comment]
It works ... you are great.  Thnx
