### ISSUE TITLE
Plugin doesn't start any content

### ISSUE THREAD

**Issue by Almuchuisle** [Dis90/plugin.video.discoveryplus#82]
Hi my plugin has stopped working, it doesn't start any content, or it starts it with audio but without images. Here a video https://ufile.io/meibu0js

**Comment by Dis90** [comment]
Please post debug log. Remember check that log doesn't contain any personal data (email etc).
https://kodi.wiki/view/Log_file/Easy

**Comment by Almuchuisle** [comment]
https://ufile.io/4vk2ztaw

**Comment by Dis90** [comment]
There's a lot 'CDVDVideoCodecAndroidMediaCodec:GetOutputPicture dequeueOutputBuffer failed' errors in your log. This is not add-on problem. Only thing I found is this https://forum.kodi.tv/showthread.php?tid=355426

Can you try example Netflix add-on?

**Comment by Almuchuisle** [comment]
I don't have a netflix account, unfortunately. It is very strange because that problem only occurs with this addon. Searching the web I saw that no one has found a solution for that error. Even though a Russian talked about disabling two-dimensional GPU graphics in developer settings, something like that. Your addon has always worked for me until now. It's a mistery

**Comment by Dis90** [comment]
You can try disabling DRM on addon settings but I don't know if that helps. It can break subtitles on some videos.

**Comment by Almuchuisle** [comment]
Disabling DRM on addon settings, apparently, everything works well. I'll test it better in the next few days. Thanks for now!
