### ISSUE TITLE
Episodes freezing and causing device reboot

### ISSUE THREAD

**Issue by JoshTheTofu** [Dis90/plugin.video.discoveryplus#83]
Hi

I have recently upgraded my Kodi to Matrix and tonight is the first time I have watched Discovery+ on it. Unfortunately each episode of the series I am trying to watch freezes and forces the device to restart.

I rolled back to old versions of InputStream Adaptive and WideVine but that didn't change anything. I also deleted cache and removed and reinstalled the add-on.

I understand that you probably want a log but I'm not sure what is best? Is the Kodi log the one you want and if so, do you need the old one or the current one?

Kind regards

Josh

**Comment by Dis90** [comment]
Hi,

Yep I need Kodi debug log https://kodi.wiki/view/Log_file/Easy
Remember edit out your personal details from log (email).

You can also try disable DRM on add-on settings.

**Comment by JoshTheTofu** [comment]
Hi

I forgot to mention that I also disabled the DRM as I saw that in a different issue on this GitHub page.

I have tried to play 2 episodes this morning and they both crashed my Raspberry Pi.

They produced two crash logs which I have attached to this comment.
[kodi_crashlog_20220410101703.log](https://github.com/Dis90/plugin.video.discoveryplus/files/8458673/kodi_crashlog_20220410101703.log)
[kodi_crashlog_20220410102335.log](https://github.com/Dis90/plugin.video.discoveryplus/files/8458674/kodi_crashlog_20220410102335.log)

Kind regards

Josh

**Comment by Dis90** [comment]
Can you test for example Netflix add-on is same thing happening with it?

**Comment by JoshTheTofu** [comment]
I was playing YouTube at 1080p when you replied and that ran perfectly.

I have just switched over to Netflix for the last 20 minutes and that runs well at 720p.

**Comment by Dis90** [comment]
Log makes me think that problem is Inputstream Adaptive but if Netflix is working then I'm not sure. Currently I'm out of ideas.

**Comment by Dis90** [comment]
This is now fixed in InputStream Adaptive 19.0.4.

**Comment by JoshTheTofu** [comment]
Hi again

I know it has been a long time, but I just wanted to confirm that it is all working now. I had to use my Pi for something else and just reinstalled a fresh version of LibreElec and it is all working well.

I also wanted to add that this plugin is one of the best, I love using it and that the new code based login system is brilliant.

Thank you for everything.
