### ISSUE TITLE
Feature Live Channels

### ISSUE THREAD

**Issue by crak3rjack** [Dis90/plugin.video.discoveryplus#85]
@Dis90 Could it possible to add the live tv channels in the menu with out having to use the iptv manager and thanks.🤞

**Comment by crak3rjack** [comment]
@Dis90 I'm in the USA

**Comment by Dis90** [comment]
Is there any real live tv channels in d+ USA?

I just realized that if I do this feature I can probably use same functions what are used in IPTV Manager integration. So this shouldn't be hard to do.

**Comment by Dis90** [comment]
Easy way is to enable IPTV Manager on add-on settings. Then you can view channels from Kodi TV section.
If you want to view channels from add-on they are usually under Home -> For You -> Channels
