### ISSUE TITLE
Mark episode as watched.

### ISSUE THREAD

**Issue by jotakswe** [Dis90/plugin.video.discoveryplus#87]
When I have finished watching an episode in a series, it is not marked as watched, but as partially watched, so I have to mark it manually as watched.
I do not know if you can see anything in a log if I post it, but let me know if you want it posted, and I will fix it.

**Comment by jotakswe** [comment]
@Dis90
I let the episodes play until the end, so it's 100%.

**Comment by Dis90** [comment]
Please check what resume time Kodi displays if you start episode again. What Kodi version you are using?

**Comment by jotakswe** [comment]
@Dis90 
I use LibreELEC 10.0.2 with Kodi (Matrix) v19.4.
Post some pictures where you can see the requested resume time.
![Bild 1](https://user-images.githubusercontent.com/59409298/176735884-0464392e-1264-4451-bc7c-e00eaadf6d8d.JPG)
![Bild 2](https://user-images.githubusercontent.com/59409298/176735889-aadf750c-4c0e-4432-a64c-b35dd62f7136.JPG)
![Bild 3](https://user-images.githubusercontent.com/59409298/176735890-314e26b4-4581-4c39-9b8e-da7224a84126.JPG)
![Bild 4](https://user-images.githubusercontent.com/59409298/176735892-43e15550-5246-4861-9481-25c784ddc348.JPG)

**Comment by jotakswe** [comment]
@Dis90 
The only things I have used are pause, jump forward and fast forward.
Log will come later tonight.

**Comment by jotakswe** [comment]
@Dis90 
Tried to do as you described, but then the episode was marked as watched after it had finished playing.
So I had to take the long road, and see the whole episode, and then it was marked as partially watched, like the ones in the photos I posted earlier.
As a result, the log file became very large, but look around line 14682, so you might find something interesting.
I tried to use "Hastebin", but it did not work, so I had to upload the file instead.

[kodi.old.log](https://github.com/Dis90/plugin.video.discoveryplus/files/9024520/kodi.old.log)

**Comment by Dis90** [comment]
I think I now know why this is not working. Now I need to find way to fix it :D
Workaround for this problem is not to use fast-forward or rewind and use skipping instead.

**Comment by Dis90** [comment]
Should be fixed in version 1.6.23. Please confirm if it now works :)

**Comment by jotakswe** [comment]
@Dis90 
Will try now tonight if it works.
Will return with the result.

**Comment by jotakswe** [comment]
@Dis90 
Cannot be updated via Kodi, v1.6.23 + matrix.1 is not available to install.
Downloads the Zip file and updates it that way.
Unfortunately, it breaks the auto-update, so has to fix it at the next release of the update.

**Comment by jotakswe** [comment]
@Dis90 
It works now!
Nice. Good work.
Thanks.
