### ISSUE TITLE
It no longer works to log in.

### ISSUE THREAD

**Issue by jotakswe** [Dis90/plugin.video.discoveryplus#88]
It no longer works to log in.
Tried the three ways described in "README.md", but it doesn't work.
Attaching the log file, if that helps.
[kodi.old.log](https://github.com/Dis90/plugin.video.discoveryplus/files/9155890/kodi.old.log)

**Comment by Dis90** [comment]
Thanks for reporting this issue. I found reason why it doesn't work. Now I need to figure out good way to fix it.

**Comment by Dis90** [comment]
@jotakswe Should be now fixed. Please try with latest version.

**Comment by jotakswe** [comment]
@Dis90 
It works now.
Thanks!

**Comment by dapuzz** [comment]
Is the fix available for kodi 18 leia too?

**Comment by Dis90** [comment]
Nope. I haven't decided whether to continue support Kodi 18 Leia. I strongly recommend to update Kodi 19 Matrix.

**Comment by Dis90** [comment]
@dapuzz I just released new version for Leia. This is probably going to be last update for Leia.

**Comment by dapuzz** [comment]
Thank you very much. It works again.
