### ISSUE TITLE
Cookies.txt addon has been removed from google.

### ISSUE THREAD

**Issue by Berringer** [Dis90/plugin.video.discoveryplus#90]
Noticed this today.
Tried other ways to login, but can't.
Tried with the firefox one, but it still does not log in.

**Comment by ulissesss** [comment]
this one works https://chrome.google.com/webstore/detail/get-cookiestxt-locally/cclelndahbckbenkjhflpdbgdldlbecc

**Comment by Berringer** [comment]
> this one works https://chrome.google.com/webstore/detail/get-cookiestxt-locally/cclelndahbckbenkjhflpdbgdldlbecc

Not for me, at all.

**Comment by fabpolli** [comment]
Linked addon worked perfectly for me. Thank You
