### ISSUE TITLE
Profiles PIN first login bypass

### ISSUE THREAD

**Issue by Liqianyu** [Dis90/plugin.video.discoveryplus#93]
If all Profiles have a PIN, add-ons enter the main Profiles without entering a PIN when they first login.
This can allow bypassing PIN protection.

**Comment by Dis90** [comment]
This is also possible on discovery+ website. You can skip profile picker by clicking d+ logo.

However I will make it mandatory to select profile after login.

**Comment by Dis90** [comment]
Fixed in 1.6.25+matrix.1
